#!/bin/sh
set -eu

if [ -z "${GNOMEF_RS_HOME:-}" ]; then
    if [ -n "${XDG_STATE_HOME:-}" ]; then
        GNOMEF_RS_HOME=$XDG_STATE_HOME/gnomeai-rs
    else
        GNOMEF_RS_HOME=${HOME:?HOME is not set}/.local/state/gnomeai-rs
    fi
    export GNOMEF_RS_HOME
fi
export GNOMEF_RS_ASSETS=${GNOMEF_RS_ASSETS:-/usr/share/gnomeai-rs}

mkdir -p "$GNOMEF_RS_HOME"

exec /usr/lib/gnomeai-rs/gnomef-web "$@"
